controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_group_velocity_controller:
      type: forward_command_controller/ForwardCommandController


wheel_group_velocity_controller:
  ros__parameters:
    joints:
      - ST3215_Servo_Motor-v1-2_Hub---Servo
      - ST3215_Servo_Motor-v1-1_Hub-2---Servo
      - ST3215_Servo_Motor-v1_Revolute-40
    interface_name: velocity
